## Art dashboard data generator: writes tools/art_dashboard/game_data.js, the
## game-side facts the dashboard page can't read for itself (a page opened
## from disk can load images and scripts, but not JSON). Re-run after changing
## a character JSON, the move bank, a portrait crop or a sidecar:
##   godot-4 --headless --path . -s tools/art_dashboard/game_data_generator.gd
## tests/unit/test_art_dashboard_data.gd fails while the file is stale.
##
## Per character, keyed by JSON file name (never characterId: saves store the
## JSON paths, so file names are the one stable key):
##   requirements  one per box, id = its COLUMNS id, in box order. Each lists the
##                 candidate files that would satisfy it (the path the JSON
##                 declares, the convention path) and whether the character's
##                 moves need it. The PAGE decides presence by loading the
##                 candidates, so status is always what's on disk right now.
##   clips         per strip: hit frame and frame timing, sidecar first, the
##                 same precedence as ClipPlayer.resolve_playback.
##   crop          the portrait crop's region on its line art.
##   class         the class it starts in (currentClass, as a class id).
##   variants      one per class below that in its promotion tree: the same
##                 character redrawn for that class, with its own full set of
##                 boxes under the file stem <id>_<class>. Moves don't change
##                 with class, so a variant needs what the base needs. Nothing
##                 in the game loads variants yet, so only convention paths
##                 count and none is "declared".
##
## `classes` is the promotion tree from Enums.CLASS_INFO, keyed by the class's
## lowercase enum name (the id in variant file names).
##
## Needs mirror UnitAnimationResolver: two reaches (1 tile = melee, 2+ =
## ranged), every attack can hit from 1 tile (targeting is distance <= range),
## Support moves are casts, an animationStyle tag forces the reach. Passives
## that add range are listed in RANGE_PASSIVES.
extends SceneTree


const CHARACTERS_DIRECTORY: String = "res://data/characters/"
const MOVE_BANK_PATH: String = "res://data/moves/basic_move_bank.json"
const OUTPUT_PATH: String = "res://tools/art_dashboard/game_data.js"
const SPRITE_DIRECTORY: String = "res://art/sprites/characters/"
const LINEART_DIRECTORY: String = "res://art/lineart_fullres/"
## Stands in for an undrawn idle; counts as no idle at all.
const PLACEHOLDER_SPRITE: String = "res://art/sprites/characters/placeholder_unit.png"

## Passive name → the damage type whose range it extends. Any bonus puts a
## 1-tile move at 2, so only the type matters. The data test fails when a
## passive script gains extra_attack_range without an entry here.
const RANGE_PASSIVES: Dictionary = {
	"Extendo": {"script": "res://scripts/combat/passives/extendo_passive.gd", "damage_type": "Physical"},
}

## The board's boxes, in order. `tier` is the color the box is needed for
## ("extra": shown, never counted); `fallback` is what the game shows while
## it's missing; `min_frames` > 1 means a still doesn't count.
const COLUMNS: Array[Dictionary] = [
	{"id": "idle", "label": "Idle", "tier": "orange", "fallback": "nothing: the unit can't appear"},
	{"id": "idle_animation", "label": "Idle anim", "tier": "orange", "fallback": "the still frame", "min_frames": 2},
	{"id": "line_art", "label": "Line art", "tier": "orange", "fallback": "a crop of the sprite's head"},
	{"id": "melee", "label": "Melee", "tier": "yellow", "fallback": "its ranged clip, else a nudge"},
	{"id": "ranged", "label": "Ranged", "tier": "yellow", "fallback": "its melee clip, else a nudge"},
	{"id": "melee_physical", "label": "Melee phys", "tier": "green", "fallback": "the plain melee clip"},
	{"id": "melee_special", "label": "Melee spec", "tier": "green", "fallback": "the plain melee clip"},
	{"id": "ranged_physical", "label": "Ranged phys", "tier": "green", "fallback": "the plain ranged clip"},
	{"id": "ranged_special", "label": "Ranged spec", "tier": "green", "fallback": "the plain ranged clip"},
	{"id": "cast", "label": "Cast", "tier": "green", "fallback": "its melee clip, then ranged"},
	{"id": "hurt", "label": "Hurt", "tier": "green", "fallback": "a code-drawn flash or fade"},
	{"id": "dodge", "label": "Dodge", "tier": "green", "fallback": "a code-drawn flash or fade"},
	{"id": "death", "label": "Death", "tier": "green", "fallback": "a code-drawn flash or fade"},
	{"id": "crit_melee", "label": "Crit melee", "tier": "extra", "fallback": "the normal clip: nothing plays crits yet"},
	{"id": "crit_ranged", "label": "Crit ranged", "tier": "extra", "fallback": "the normal clip: nothing plays crits yet"},
]

const HEADER: String = "// Generated by tools/art_dashboard/game_data_generator.gd. Don't edit;\n// re-run: godot-4 --headless --path . -s tools/art_dashboard/game_data_generator.gd\n"


func _initialize() -> void:
	var file := FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Can't write %s" % OUTPUT_PATH)
		quit(1)
		return
	file.store_string(render(build_data()))
	file.close()
	print("Wrote %s" % OUTPUT_PATH)
	quit(0)


static func render(data: Dictionary) -> String:
	return HEADER + "window.ART_DASHBOARD_DATA = " + JSON.stringify(data, "\t", true) + ";\n"


static func build_data() -> Dictionary:
	var move_bank: Dictionary = read_json(MOVE_BANK_PATH)
	var characters: Array[Dictionary] = []
	for path: String in character_files():
		var character: Dictionary = read_json(path)
		if not character.is_empty():
			characters.append(character_entry(path.get_file().get_basename(), character, move_bank))
	# `convention` tells the page where each box's file goes ({id} = character).
	var columns: Array[Dictionary] = []
	for column: Dictionary in COLUMNS:
		var entry := column.duplicate()
		entry["convention"] = convention_path(column.id, "{id}").trim_prefix("res://")
		columns.append(entry)
	var character_ids := characters.map(func(entry: Dictionary) -> String: return entry.id)
	for entry: Dictionary in characters:
		for variant: Dictionary in entry.variants:
			if character_ids.has(variant.id):
				push_error("Art dashboard: %s's %s variant shares its files with the character %s" % [
						entry.id, variant["class"], variant.id])
	return {"columns": columns, "classes": class_entries(), "characters": characters}


## Every class with its tier and the classes it promotes into.
static func class_entries() -> Array[Dictionary]:
	var entries: Array[Dictionary] = []
	for character_class: int in Enums.CLASS_INFO:
		var info: Dictionary = Enums.CLASS_INFO[character_class]
		entries.append({
			"id": class_id(character_class),
			"name": str(info.display_name),
			"tier": int(info.tier),
			"promotes_to": (info.get("promotes_to", []) as Array).map(
					func(promotion: int) -> String: return class_id(promotion)),
		})
	return entries


static func class_id(character_class: int) -> String:
	return str(Enums.CharacterClass.find_key(character_class)).to_lower()


## currentClass the way CharacterDataLoader reads it: "Void Knight" → void_knight.
static func character_class_id(character: Dictionary) -> String:
	var id := str(character.get("currentClass", "Spaceman")).to_lower().replace(" ", "_")
	if not Enums.CharacterClass.has(id.to_upper()):
		push_error("Art dashboard: no class '%s' in Enums.CharacterClass" % id)
	return id


## Every class below `start` in the promotion tree, nearest tier first.
static func promotions_below(start: String) -> Array[String]:
	var found: Array[String] = []
	var frontier: Array[String] = [start]
	while not frontier.is_empty():
		var info: Dictionary = Enums.CLASS_INFO.get(Enums.CharacterClass.get(frontier.pop_front().to_upper(), -1), {})
		for promotion: int in info.get("promotes_to", []):
			if not found.has(class_id(promotion)):
				found.append(class_id(promotion))
				frontier.append(class_id(promotion))
	return found


static func character_entry(character_id: String, character: Dictionary, move_bank: Dictionary) -> Dictionary:
	var result := {
		"id": character_id,
		"name": str(character.get("characterName", character_id)),
		"class": character_class_id(character),
	}
	result.merge(art_entry(character_id, character, move_bank))
	# Only the moves carry over: every file a variant has is its own.
	var moves_only := {"basePoolMoves": character.get("basePoolMoves", []),
			"basePoolPassives": character.get("basePoolPassives", [])}
	var variants: Array[Dictionary] = []
	for promotion: String in promotions_below(result["class"]):
		var variant := {"class": promotion}
		variant.merge(art_entry(character_id + "_" + promotion, moves_only, move_bank))
		variants.append(variant)
	result["variants"] = variants
	return result


## The boxes for one set of art (a character, or one of its class variants).
static func art_entry(character_id: String, character: Dictionary, move_bank: Dictionary) -> Dictionary:
	var kit := kit_for(character.get("basePoolMoves", []), character.get("basePoolPassives", []), move_bank)
	var declared_clips: Dictionary = {}
	var animations: Dictionary = character.get("animations", {})
	for key: Variant in animations:
		declared_clips[str(key).to_lower()] = str(animations[key].get("path", ""))

	var sprite_path := str(character.get("sprite", {}).get("sheetPath", ""))
	if sprite_path == PLACEHOLDER_SPRITE:
		sprite_path = ""
	var idle_candidates := candidates_for(sprite_path, convention_path("idle", character_id))
	var lineart_candidates := candidates_for(str(character.get("lineartPath", "")),
			convention_path("line_art", character_id))

	var requirements: Array[Dictionary] = [
		requirement("idle", true, idle_candidates),
		requirement("idle_animation", true, idle_candidates),
		requirement("line_art", true, lineart_candidates),
	]
	for reach: String in ["melee", "ranged"]:
		requirements.append(requirement(reach, kit.reaches.has(reach),
				clip_candidates(character_id, [reach, reach + "_physical", reach + "_special"], declared_clips)))
	# A plain reach clip covers both kinds, so it stands in for a kind's own
	# clip: the box counts, and says whose clip it's showing.
	for reach: String in ["melee", "ranged"]:
		for kind: String in ["physical", "special"]:
			var pair := reach + "_" + kind
			requirements.append(requirement(pair, kit.pairs.has(pair),
					clip_candidates(character_id, [pair, reach], declared_clips)))
	requirements.append(requirement("cast", kit.casts,
			clip_candidates(character_id, ["cast"], declared_clips)))
	for reaction: String in ["hurt", "dodge", "death"]:
		requirements.append(requirement(reaction, true,
				clip_candidates(character_id, [reaction], declared_clips)))
	for reach: String in ["melee", "ranged"]:
		requirements.append(requirement("crit_" + reach, kit.reaches.has(reach),
				clip_candidates(character_id, ["crit_" + reach], declared_clips)))

	var clips: Dictionary = {}
	for entry: Dictionary in requirements:
		for candidate: Dictionary in entry.candidates:
			if entry.id == "line_art" or clips.has(candidate.path):
				continue
			var timing := clip_timing("res://" + candidate.path, animations)
			if not timing.is_empty():
				clips[candidate.path] = timing

	var result := {"id": character_id, "requirements": requirements, "clips": clips}
	var crop := portrait_crop(character, character_id)
	if not crop.is_empty():
		result["crop"] = crop
	return result


## Which reaches, reach × kind pairs and casts the character's move pool uses.
static func kit_for(move_names: Array, passive_names: Array, move_bank: Dictionary) -> Dictionary:
	var extended_types: Array[String] = []
	for passive_name: Variant in passive_names:
		if RANGE_PASSIVES.has(passive_name):
			extended_types.append(RANGE_PASSIVES[passive_name].damage_type)
	var reaches: Dictionary = {}
	var pairs: Dictionary = {}
	var casts := false
	for move_name: Variant in move_names:
		var move: Dictionary = move_bank.get(move_name, {})
		if move.is_empty():
			push_error("Art dashboard: move '%s' isn't in the move bank" % move_name)
			continue
		var damage_type := str(move.get("damageType", ""))
		if damage_type == "Support":
			casts = true
			continue
		var kind := "special" if damage_type == "Special" else "physical"
		var attack_range := int(move.get("range", 1)) + (1 if extended_types.has(damage_type) else 0)
		var style := str(move.get("animationStyle", "")).to_lower()
		var move_reaches: Array[String] = ["melee"]
		if style == "melee" or style == "ranged":
			move_reaches = [style]
		elif attack_range >= 2:
			move_reaches = ["melee", "ranged"]
		for reach: String in move_reaches:
			reaches[reach] = true
			pairs[reach + "_" + kind] = true
	return {"reaches": reaches, "pairs": pairs, "casts": casts}


## Tier and min_frames come from the box's COLUMNS entry: one home each.
static func requirement(id: String, needed: bool, candidates: Array[Dictionary]) -> Dictionary:
	var column := column_for(id)
	var entry := {"id": id, "tier": column.tier, "needed": needed, "candidates": candidates}
	if column.has("min_frames"):
		entry["min_frames"] = column.min_frames
	return entry


static func column_for(id: String) -> Dictionary:
	for column: Dictionary in COLUMNS:
		if column.id == id:
			return column
	assert(false, "Art dashboard: no COLUMNS entry for box '%s'" % id)
	return {}


## Where a box's file goes. Sprites: the tag exporter writes tag <tag> of
## <character>.aseprite to <character>/<tag>.png, so the path names both.
static func convention_path(box_id: String, character_id: String) -> String:
	if box_id == "line_art":
		return LINEART_DIRECTORY + character_id + ".png"
	var tag := "idle" if box_id == "idle_animation" else box_id
	return SPRITE_DIRECTORY + character_id + "/" + tag + ".png"


## Each candidate carries `clip`, the vocabulary key it is; the page calls a
## candidate whose clip isn't the box's own a stand-in.
static func clip_candidates(character_id: String, keys: Array, declared_clips: Dictionary) -> Array[Dictionary]:
	var merged: Array[Dictionary] = []
	for key: String in keys:
		for candidate: Dictionary in candidates_for(str(declared_clips.get(key, "")),
				convention_path(key, character_id)):
			candidate["clip"] = key
			var existing := merged.filter(func(other: Dictionary) -> bool: return other.path == candidate.path)
			if existing.is_empty():
				merged.append(candidate)
			else:
				existing[0].declared = existing[0].declared or candidate.declared
				existing[0].convention = existing[0].convention or candidate.convention
	return merged


## The declared path (what the game loads) first, then the convention path.
## Paths are repo-relative so the page can prefix its way to the repo root.
## A declared path off the convention carries `rename_to`: the board's rename list.
static func candidates_for(declared_path: String, convention_path: String) -> Array[Dictionary]:
	var convention := convention_path.trim_prefix("res://")
	if declared_path == convention_path:
		return [{"path": convention, "declared": true, "convention": true}]
	var result: Array[Dictionary] = []
	if not declared_path.is_empty():
		result.append({"path": declared_path.trim_prefix("res://"), "declared": true,
				"convention": false, "rename_to": convention})
	result.append({"path": convention, "declared": false, "convention": true})
	return result


## Hit frame, frame durations, fps and (idle) art bounds for a strip. Sidecar
## values win over the JSON entry, as in ClipPlayer; {} when neither exists.
static func clip_timing(strip_path: String, animations: Dictionary) -> Dictionary:
	var timing: Dictionary = {}
	for key: Variant in animations:
		var entry: Dictionary = animations[key]
		if str(entry.get("path", "")) != strip_path:
			continue
		if entry.has("hit_frame"):
			timing["hit_frame"] = int(entry.hit_frame)
		if entry.has("fps"):
			timing["fps"] = int(entry.fps)
	var sidecar := read_json(strip_path.trim_suffix(".png") + ".json", false)
	if sidecar.has("hit_frame"):
		timing["hit_frame"] = int(sidecar.hit_frame)
	if sidecar.has("frame_durations_ms"):
		timing["frame_durations_ms"] = (sidecar.frame_durations_ms as Array).map(
				func(milliseconds: Variant) -> int: return int(milliseconds))
	if sidecar.has("art_bounds"):
		var bounds: Dictionary = sidecar.art_bounds
		timing["art_bounds"] = {"left": int(bounds.left), "top": int(bounds.top),
				"right": int(bounds.right), "bottom": int(bounds.bottom)}
	return timing


## The portrait crop's atlas path and region, read from the .tres text so a
## checkout that was never imported still works. {} when there's no crop.
static func portrait_crop(character: Dictionary, character_id: String) -> Dictionary:
	var crop_path := str(character.get("lineartAtlases", {}).get("portrait", ""))
	if crop_path.is_empty():
		crop_path = LINEART_DIRECTORY + character_id + "_portrait.tres"
	if not FileAccess.file_exists(crop_path):
		return {}
	var text := FileAccess.get_file_as_string(crop_path)
	var atlas := RegEx.create_from_string('ext_resource type="Texture2D"[^\\n]*path="([^"]+)"').search(text)
	var region := RegEx.create_from_string("region = Rect2\\(([-\\d.]+), ([-\\d.]+), ([-\\d.]+), ([-\\d.]+)\\)").search(text)
	if atlas == null or region == null:
		push_error("Art dashboard: can't read the crop in %s" % crop_path)
		return {}
	return {
		"atlas": atlas.get_string(1).trim_prefix("res://"),
		"x": int(float(region.get_string(1))), "y": int(float(region.get_string(2))),
		"width": int(float(region.get_string(3))), "height": int(float(region.get_string(4))),
	}


static func character_files() -> Array[String]:
	var files: Array[String] = []
	for file_name: String in DirAccess.get_files_at(CHARACTERS_DIRECTORY):
		if file_name.ends_with(".json"):
			files.append(CHARACTERS_DIRECTORY + file_name)
	files.sort()
	return files


static func read_json(path: String, required: bool = true) -> Dictionary:
	if not FileAccess.file_exists(path):
		if required:
			push_error("Art dashboard: missing %s" % path)
		return {}
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(path))
	if parsed is Dictionary:
		return parsed
	push_error("Art dashboard: %s isn't a JSON object" % path)
	return {}
